#include <omp.h>
#include <cstdlib>
#include <iostream>
#include <cmath>

using namespace std;

void test_routine(double *a, int N)
{

  for (int i = 0; i != N; ++i){
    a[i * N + i] = sqrt(a[i * N + i]);

    for (int j = i + 1; j < N; ++j){
      a[j * N + i] = a[j * N + i] / a[i * N + i];
    }

    for (int j = i + 1; j < N; ++j){
      for (int k = i + 1; k <= j; ++k){
        a[j * N + k] -= a[j * N + i] * a[k * N + i];
      }
    }
  }
}

/**
 * Unrolled loops for N=2 (Generated by Gemini 3 Flash)
 * Made not for execution, but for my own visualization purposes
 */
void test_routine_N2(double *a) {
  // --- i = 0 ---
  a[0] = sqrt(a[0]);               // Node 1

  // Inner j loop (j=1)
  a[2] = a[2] / a[0];              // Node 2 (Depends on Node 1)

  // Triple loop (j=1, k=1)
  a[3] -= a[2] * a[2];             // Node 3 (Depends on Node 2)

  // --- i = 1 ---
  a[3] = sqrt(a[3]);               // Node 4 (Depends on Node 3)
}

/**
 * Unrolled loops for N=3 (Generated by Gemini 3 Flash)
 * Made not for execution, but for my own visualization purposes
 */
void test_routine_N3(double *a) {
  // --- i = 0 ---
  a[0] = sqrt(a[0]);               // Update Diagonal
  a[3] = a[3] / a[0];              // Column 0 updates
  a[6] = a[6] / a[0];

  a[4] -= a[3] * a[3];             // Row 1 & 2 updates using Col 0
  a[7] -= a[6] * a[3];
  a[8] -= a[6] * a[6];

  // --- i = 1 ---
  a[4] = sqrt(a[4]);               // Update Diagonal
  a[7] = a[7] / a[4];              // Column 1 update

  a[8] -= a[7] * a[7];             // Row 2 update using Col 1

  // --- i = 2 ---
  a[8] = sqrt(a[8]);               // Final Diagonal
}

int main()
{

  unsigned long long st, et;

  int N = 10;

  double *a, *b;
  a = (double *)calloc(N * N, sizeof(double));
  b = (double *)calloc(N * N, sizeof(double));

  // create lower tri matrix
  for (int i = 0; i < N; ++i)
    for (int j = 0; j <= i; ++j)
      a[i * N + j] = rand() % 10 + 1;

  // compute A * A'
  for (int i = 0; i < N; ++i)
    for (int j = 0; j < N; ++j)
      for (int k = 0; k < N; ++k)
        b[i * N + j] += a[i * N + k] * a[j * N + k];

  test_routine(b, N);

  bool correct = true;
  for (int i = 0; i < N; ++i)
    for (int j = 0; j <= i; ++j)
      correct &= (fabs(a[i * N + j] - b[i * N + j]) < 1e-7);

  cout << (correct ? "Yes" : "No") << endl;

  free(a);
  free(b);

  return 0;
}
